---
title: "SFB Projections"
description: |
  This site hosts projections for the [Scott Fish Bowl 11](https://scottfishbowl.com), as created by the [ffsimulator](https://ffsimulator.ffverse.com) R package.
  
  Projections last updated on 2021-09-05.
site: 
  distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(arrow)
library(reactable)
library(crosstalk)
library(janitor)
library(tidyverse)
library(ffscrapr)
library(htmltools)
```

## Main Contest

```{r layout = "l-body-outset"}
main_rosters <- arrow::read_parquet("data/main_2021-09-05/rosters.parquet")

main_franchises <- main_rosters %>% 
  select(
    franchise_id,
    franchise_name,
    league_id,
    division_id,
    division_name
  ) %>% 
  distinct()

main_percentiles <- arrow::read_parquet("data/main_2021-09-05/summary_season_adp.parquet") %>% 
  group_by(season) %>% 
  mutate(rank = rank(-points_for)) %>% 
  group_by(league_id, franchise_id) %>% 
  summarise(
    percentiles = c(0.05,0.25,0.5,0.75,0.95),
    points = quantile(points_for,percentiles) %>% round(),
    rank = quantile(rank,1-percentiles) %>% round() %>% scales::ordinal(big.mark = ""),
    percentiles = scales::ordinal(percentiles * 100),
    outcome = glue::glue("{points} ({rank})"),
  ) %>% 
  ungroup() %>% 
  select(-points,-rank) %>% 
  pivot_wider(
    names_from = "percentiles",
    values_from = "outcome"
  )

main_simulation <- arrow::read_parquet("data/main_2021-09-05/summary_simulation_adp.parquet") %>% 
  left_join(
    x = main_franchises,
    y = .,
    by = c("league_id","franchise_id","franchise_name")
  ) %>% 
  mutate(
    franchise_name = dp_clean_html(franchise_name) %>% str_squish(),
    franchise_url = glue::glue("https://www03.myfantasyleague.com/2021/options?L={league_id}&F={franchise_id}&O=07"),
    franchise_label = map2_chr(franchise_name,franchise_url,~as.character(htmltools::tags$a(.x,href = .y))),
    rank = rank(-points_for, ties.method = "random")
  ) %>% 
  select(
    league_id,
    franchise_id, 
    franchise_name,
    franchise_label,
    division_name,
    rank,
    points_for,
    h2h_winpct,
    allplay_winpct
  ) %>% 
  left_join(
    main_percentiles,
    by = c("league_id","franchise_id")
  ) %>% 
  select(
    "Franchise Name" = "franchise_name",
    "Franchise Label" = "franchise_label",
    "Rank" = "rank",
    "Points For" = "points_for",
    "H2H Win %" = "h2h_winpct",
    "AllPlay Win %" = "allplay_winpct",
    "5th",
    "25th",
    "50th",
    "75th",
    "95th",
    "Division Name" = "division_name"
  ) %>% 
  arrange(Rank)

crosstalk_main <- SharedData$new(main_simulation)

bscols(
  widths = c(4,4),
  filter_select("main_franchise_name", "Franchise Name", crosstalk_main, ~`Franchise Name`),
  filter_select("main_division", "Division Select", crosstalk_main, ~`Division Name`)
)

crosstalk_main %>% 
  reactable(
    elementId = "sfb_main_sim",
    striped = TRUE,
    highlight = TRUE,
    resizable = TRUE,
    compact = FALSE,
    width = 'auto',
    columnGroups =  list(
      colGroup(name = "Percentile Outcomes - Points (Rank)",
               columns = c("5th", "25th","50th","75th","95th")),
      colGroup(
        name = "Overall",
        headerStyle = list(borderRight = "1px solid #eee"),
        columns = c("Rank", "Points For","H2H Win %", "AllPlay Win %"))
    ),
    columns = list(
      `Franchise Name` = colDef(show = FALSE),
      `Franchise Label` = colDef(minWidth = 150,sticky = "left", html = TRUE, name = "Franchise Name"),
      `Division Name` = colDef(minWidth = 100),
      `Rank` = colDef(minWidth = 75,
                      style = list(borderLeft = "1px solid #eee")
                      ),
      `H2H Win %`= colDef(minWidth = 75,
                          format = colFormat(percent = TRUE)),
      `AllPlay Win %`= colDef(minWidth = 75,
                          format = colFormat(percent = TRUE),
                      style = list(borderRight = "1px solid #eee"),
                      headerStyle = list(borderRight = "1px solid #eee")),
      `Points For`= colDef(minWidth = 75,
                          format = colFormat(digits = 1))
      ),
    fullWidth = TRUE,
    defaultSortOrder = "asc",
    defaultSorted = c("Rank"),
    defaultPageSize = 25,
    pageSizeOptions = c(25,50,100,500),
    showPageSizeOptions = TRUE
  )

```

## Satellite Contest

```{r layout = "l-body-outset"}
satellite_rosters <- arrow::read_parquet("data/satellite_2021-09-05/rosters.parquet")

satellite_franchises <- satellite_rosters %>% 
  select(
    franchise_id,
    franchise_name,
    league_id,
    division_id,
    division_name
  ) %>% 
  distinct()

satellite_percentiles <- arrow::read_parquet("data/satellite_2021-09-05/summary_season_adp.parquet") %>% 
  group_by(season) %>% 
  mutate(rank = rank(-points_for)) %>% 
  group_by(league_id, franchise_id) %>% 
  summarise(
    percentiles = c(0.05,0.25,0.5,0.75,0.95),
    points = quantile(points_for,percentiles) %>% round(),
    rank = quantile(rank,1-percentiles) %>% round() %>% scales::ordinal(big.mark = ""),
    percentiles = scales::ordinal(percentiles * 100),
    outcome = glue::glue("{points} ({rank})"),
  ) %>% 
  ungroup() %>% 
  select(-points,-rank) %>% 
  pivot_wider(
    names_from = "percentiles",
    values_from = "outcome"
  )

satellite_simulation <- arrow::read_parquet("data/satellite_2021-09-05/summary_simulation_adp.parquet") %>% 
  left_join(
    x = satellite_franchises,
    y = .,
    by = c("league_id","franchise_id","franchise_name")
  ) %>% 
  mutate(
    franchise_name = dp_clean_html(franchise_name) %>% str_squish(),
    franchise_url = glue::glue("https://www03.myfantasyleague.com/2021/options?L={league_id}&F={franchise_id}&O=07"),
    franchise_label = map2_chr(franchise_name,franchise_url,~as.character(htmltools::tags$a(.x,href = .y))),
    rank = rank(-points_for, ties.method = "random")
  ) %>% 
  select(
    league_id,
    franchise_id, 
    franchise_name,
    franchise_label,
    division_name,
    rank,
    points_for,
    h2h_winpct,
    allplay_winpct
  ) %>% 
  left_join(
    satellite_percentiles,
    by = c("league_id","franchise_id")
  ) %>% 
  select(
    "Franchise Name" = "franchise_name",
    "Franchise Label" = "franchise_label",
    "Rank" = "rank",
    "Points For" = "points_for",
    "5th",
    "25th",
    "50th",
    "75th",
    "95th",
    "League ID" = "league_id",
    "Division Name" = "division_name"
  ) %>% 
  arrange(Rank)

crosstalk_satellite <- SharedData$new(satellite_simulation)

bscols(
  widths = c(4,4,4),
  filter_select("satellite_franchise_name", "Franchise Name", crosstalk_satellite, ~`Franchise Name`),
  filter_select("satellite_leagueid","League ID", crosstalk_satellite, ~`League ID`),
  filter_select("satellite_division", "Division Select", crosstalk_satellite, ~`Division Name`)
)

crosstalk_satellite %>% 
  reactable(
    elementId = "sfb_satellite_sim",
    striped = TRUE,
    highlight = TRUE,
    resizable = TRUE,
    compact = FALSE,
    width = 'auto',
    columnGroups =  list(
      colGroup(name = "Percentile Outcomes - Points (Rank)",
               columns = c("5th", "25th","50th","75th","95th")
               ),
      colGroup(
        name = "Overall",
        headerStyle = list(borderRight = "1px solid #eee"),
        columns = c("Rank", "Points For"))
    ),
    columns = list(
      `Franchise Name` = colDef(show = FALSE),
      `Franchise Label` = colDef(minWidth = 150,sticky = "left", html = TRUE, name = "Franchise Name"),
      `Division Name` = colDef(minWidth = 100),
      `Rank` = colDef(minWidth = 75, style = list(borderLeft = "1px solid #eee")),
      `Points For`= colDef(minWidth = 75,
                           format = colFormat(digits = 1),
                           style = list(borderRight = "1px solid #eee"),
                           headerStyle = list(borderRight = "1px solid #eee"))
    ),
    fullWidth = TRUE,
    defaultSortOrder = "asc",
    defaultSorted = c("Rank"),
    defaultPageSize = 25,
    pageSizeOptions = c(25,50,100,500),
    showPageSizeOptions = TRUE
  )


```
